language: node_js
before_install:
  - chmod +x minify.sh
script: ./minify.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: dev-travis